"""empty message

Revision ID: 46535ea6cf80
Revises: 637f884d5087
Create Date: 2018-03-26 15:59:25.004516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46535ea6cf80'
down_revision = '637f884d5087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
