"""empty message

Revision ID: 7c9e27cfb099
Revises: 46535ea6cf80
Create Date: 2018-03-29 11:37:09.113199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c9e27cfb099'
down_revision = '46535ea6cf80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('busytimes', sa.Column('event_id', sa.Integer(), nullable=True))
    op.drop_constraint('busytimes_ibfk_1', 'busytimes', type_='foreignkey')
    op.create_foreign_key(None, 'busytimes', 'events', ['event_id'], ['id'])
    op.drop_column('busytimes', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('busytimes', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'busytimes', type_='foreignkey')
    op.create_foreign_key('busytimes_ibfk_1', 'busytimes', 'users', ['user_id'], ['id'])
    op.drop_column('busytimes', 'event_id')
    # ### end Alembic commands ###
