"""empty message

Revision ID: ba3bad8e5870
Revises: 7c9e27cfb099
Create Date: 2018-04-18 21:20:05.662801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba3bad8e5870'
down_revision = '7c9e27cfb099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('busytimes', sa.Column('end_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('busytimes', sa.Column('start_date', sa.TIMESTAMP(), nullable=True))
    op.drop_column('busytimes', 'end_time')
    op.drop_column('busytimes', 'start_time')
    op.drop_column('events', 'start_date')
    op.drop_column('events', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_date', mysql.DATETIME(), nullable=True))
    op.add_column('events', sa.Column('start_date', mysql.DATETIME(), nullable=True))
    op.add_column('busytimes', sa.Column('start_time', mysql.DATETIME(), nullable=True))
    op.add_column('busytimes', sa.Column('end_time', mysql.DATETIME(), nullable=True))
    op.drop_column('busytimes', 'start_date')
    op.drop_column('busytimes', 'end_date')
    # ### end Alembic commands ###
