"""empty message

Revision ID: da30c3efa003
Revises: fad83e7443c4
Create Date: 2018-03-25 21:28:52.773690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da30c3efa003'
down_revision = 'fad83e7443c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_interests_name'), 'interests', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interests_name'), table_name='interests')
    # ### end Alembic commands ###
